import 'package:flutter/material.dart';

@immutable
class ListeningTopic {
  const ListeningTopic({
    required this.titleVi,
    required this.titleZh,
    required this.icon,
    required this.background,
    required this.foreground,
    required this.completed,
    this.total = 10,
    this.imagePath,
  });

  final String titleVi;
  final String titleZh;
  final IconData icon;
  final Color background;
  final Color foreground;
  final int completed;
  final int total;
  final String? imagePath;
}

@immutable
class ListeningAgeCatalog {
  const ListeningAgeCatalog({
    required this.startAge,
    required this.endAge,
    required this.topics,
    required this.continueTopicIndex,
  });

  final int startAge;
  final int endAge;
  final List<ListeningTopic> topics;
  final int continueTopicIndex;

  String get id => '$startAge-$endAge';
}

const _indigo = Color(0xFF3D4DD6);
const _blue = Color(0xFF2684D9);
const _green = Color(0xFF23A05A);
const _orange = Color(0xFFE36A3D);
const _amber = Color(0xFFE28A21);
const _coral = Color(0xFFF36B5F);
const _purpleWash = Color(0xFFF1EEFF);
const _blueWash = Color(0xFFE9F5FF);
const _greenWash = Color(0xFFEAF7EE);
const _orangeWash = Color(0xFFFFF0E4);
const _amberWash = Color(0xFFFFF4DF);
const _coralWash = Color(0xFFFFECE7);

/// The lightweight journey-card catalog mirrors the published V4 lesson
/// content. `assets/data/listening_lessons.json` remains the source of truth
/// for lesson payloads; the alignment test keeps this UI metadata in sync.
const listeningCatalogs = <ListeningAgeCatalog>[
  ListeningAgeCatalog(
    startAge: 3,
    endAge: 5,
    continueTopicIndex: 0,
    topics: <ListeningTopic>[
      ListeningTopic(
        titleVi: 'Bảng chữ cái',
        titleZh: '字母表',
        icon: Icons.abc_rounded,
        background: _purpleWash,
        foreground: _indigo,
        completed: 0,
        total: 3,
        imagePath: 'assets/images/topics/fun-alphabet.jpg',
      ),
      ListeningTopic(
        titleVi: 'Số đếm',
        titleZh: '数字',
        icon: Icons.pin_rounded,
        background: _amberWash,
        foreground: _amber,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/counting-1-10.jpg',
      ),
      ListeningTopic(
        titleVi: 'Màu sắc',
        titleZh: '颜色',
        icon: Icons.palette_rounded,
        background: _coralWash,
        foreground: _coral,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/colors-shapes.jpg',
      ),
      ListeningTopic(
        titleVi: 'Hình dạng',
        titleZh: '形状',
        icon: Icons.category_rounded,
        background: _blueWash,
        foreground: _blue,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/colors-shapes.jpg',
      ),
      ListeningTopic(
        titleVi: 'Động vật',
        titleZh: '动物',
        icon: Icons.pets_rounded,
        background: _greenWash,
        foreground: _green,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/cute-animals.jpg',
      ),
      ListeningTopic(
        titleVi: 'Cơ thể của mình',
        titleZh: '我的身体',
        icon: Icons.accessibility_new_rounded,
        background: _orangeWash,
        foreground: _orange,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/my-body.jpg',
      ),
      ListeningTopic(
        titleVi: 'Đồ ăn',
        titleZh: '食物',
        icon: Icons.restaurant_rounded,
        background: _amberWash,
        foreground: _amber,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/food-drinks-3-5.jpg',
      ),
      ListeningTopic(
        titleVi: 'Gia đình của mình',
        titleZh: '我的家人',
        icon: Icons.family_restroom_rounded,
        background: _purpleWash,
        foreground: _indigo,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/my-family.jpg',
      ),
      ListeningTopic(
        titleVi: 'Thời tiết',
        titleZh: '天气',
        icon: Icons.wb_sunny_rounded,
        background: _blueWash,
        foreground: _blue,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/weather-clothes-6-7.jpg',
      ),
      ListeningTopic(
        titleVi: 'Một ngày của mình',
        titleZh: '我的一天',
        icon: Icons.directions_run_rounded,
        background: _greenWash,
        foreground: _green,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/daily-activities-6-7.jpg',
      ),
    ],
  ),
  ListeningAgeCatalog(
    startAge: 6,
    endAge: 7,
    continueTopicIndex: 0,
    topics: <ListeningTopic>[
      ListeningTopic(
        titleVi: 'Từ vựng theo chữ cái',
        titleZh: '字母词汇',
        icon: Icons.abc_rounded,
        background: _purpleWash,
        foreground: _indigo,
        completed: 0,
        total: 3,
        imagePath: 'assets/images/topics/fun-alphabet.jpg',
      ),
      ListeningTopic(
        titleVi: 'Những con số quanh mình',
        titleZh: '身边的数字',
        icon: Icons.numbers_rounded,
        background: _amberWash,
        foreground: _amber,
        completed: 0,
        total: 3,
        imagePath: 'assets/images/topics/numbers-time.jpg',
      ),
      ListeningTopic(
        titleVi: 'Động vật thú vị',
        titleZh: '有趣的动物',
        icon: Icons.pets_rounded,
        background: _greenWash,
        foreground: _green,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/cute-animals.jpg',
      ),
      ListeningTopic(
        titleVi: 'Món ăn mình thích',
        titleZh: '我喜欢的食物',
        icon: Icons.lunch_dining_rounded,
        background: _orangeWash,
        foreground: _orange,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/favorite-food.jpg',
      ),
      ListeningTopic(
        titleVi: 'Đồ dùng của mình',
        titleZh: '我的物品',
        icon: Icons.backpack_rounded,
        background: _blueWash,
        foreground: _blue,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/my-toys.jpg',
      ),
      ListeningTopic(
        titleVi: 'Cơ thể khỏe mạnh',
        titleZh: '健康的我',
        icon: Icons.accessibility_new_rounded,
        background: _greenWash,
        foreground: _green,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/my-body.jpg',
      ),
      ListeningTopic(
        titleVi: 'Ở trường',
        titleZh: '在学校',
        icon: Icons.school_rounded,
        background: _purpleWash,
        foreground: _indigo,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/school-day.jpg',
      ),
      ListeningTopic(
        titleVi: 'Bạn bè của mình',
        titleZh: '我的朋友',
        icon: Icons.groups_rounded,
        background: _blueWash,
        foreground: _blue,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/friends-8-10.jpg',
      ),
      ListeningTopic(
        titleVi: 'Những nơi gần đây',
        titleZh: '附近的地方',
        icon: Icons.place_rounded,
        background: _amberWash,
        foreground: _amber,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/city-travel-11-12.jpg',
      ),
      ListeningTopic(
        titleVi: 'Cuối tuần của mình',
        titleZh: '我的周末',
        icon: Icons.weekend_rounded,
        background: _coralWash,
        foreground: _coral,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/weekend-plans.jpg',
      ),
    ],
  ),
  ListeningAgeCatalog(
    startAge: 8,
    endAge: 10,
    continueTopicIndex: 0,
    topics: <ListeningTopic>[
      ListeningTopic(
        titleVi: 'Lịch sinh hoạt của mình',
        titleZh: '我的日程',
        icon: Icons.calendar_month_rounded,
        background: _purpleWash,
        foreground: _indigo,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/daily-activities-6-7.jpg',
      ),
      ListeningTopic(
        titleVi: 'Cuộc sống ở trường',
        titleZh: '校园生活',
        icon: Icons.school_rounded,
        background: _blueWash,
        foreground: _blue,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/school-life-11-12.jpg',
      ),
      ListeningTopic(
        titleVi: 'Sở thích của mình',
        titleZh: '我的爱好',
        icon: Icons.sports_soccer_rounded,
        background: _greenWash,
        foreground: _green,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/hobbies-sports-8-10.jpg',
      ),
      ListeningTopic(
        titleVi: 'Đi quanh thành phố',
        titleZh: '城市漫游',
        icon: Icons.directions_bus_rounded,
        background: _coralWash,
        foreground: _coral,
        completed: 0,
        total: 3,
        imagePath: 'assets/images/topics/city-travel-11-12.jpg',
      ),
      ListeningTopic(
        titleVi: 'Kế hoạch theo thời tiết',
        titleZh: '天气计划',
        icon: Icons.wb_sunny_rounded,
        background: _amberWash,
        foreground: _amber,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/weather-clothes-6-7.jpg',
      ),
      ListeningTopic(
        titleVi: 'Công nghệ',
        titleZh: '科技',
        icon: Icons.devices_rounded,
        background: _blueWash,
        foreground: _blue,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/phone-internet-11-12.jpg',
      ),
      ListeningTopic(
        titleVi: 'Lựa chọn khi mua sắm',
        titleZh: '购物选择',
        icon: Icons.shopping_bag_rounded,
        background: _orangeWash,
        foreground: _orange,
        completed: 0,
        total: 3,
        imagePath: 'assets/images/topics/shopping-8-10.jpg',
      ),
      ListeningTopic(
        titleVi: 'Bạn bè và cảm xúc',
        titleZh: '朋友与情绪',
        icon: Icons.sentiment_satisfied_alt_rounded,
        background: _greenWash,
        foreground: _green,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/friends-8-10.jpg',
      ),
      ListeningTopic(
        titleVi: 'Chuyện gì đã xảy ra?',
        titleZh: '发生了什么？',
        icon: Icons.forum_rounded,
        background: _purpleWash,
        foreground: _indigo,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/feelings-opinions-11-12.jpg',
      ),
      ListeningTopic(
        titleVi: 'Ngày đi chơi',
        titleZh: '出游日',
        icon: Icons.weekend_rounded,
        background: _orangeWash,
        foreground: _orange,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/eating-out-8-10.jpg',
      ),
    ],
  ),
  ListeningAgeCatalog(
    startAge: 11,
    endAge: 12,
    continueTopicIndex: 0,
    topics: <ListeningTopic>[
      ListeningTopic(
        titleVi: 'Tuần của mình',
        titleZh: '我的一周',
        icon: Icons.calendar_month_rounded,
        background: _purpleWash,
        foreground: _indigo,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/weekend-plans.jpg',
      ),
      ListeningTopic(
        titleVi: 'Học hiệu quả hơn',
        titleZh: '高效学习',
        icon: Icons.school_rounded,
        background: _blueWash,
        foreground: _blue,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/study-goals.jpg',
      ),
      ListeningTopic(
        titleVi: 'Điểm mạnh của mình',
        titleZh: '我的优势',
        icon: Icons.star_rounded,
        background: _greenWash,
        foreground: _green,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/detailed-introduction.jpg',
      ),
      ListeningTopic(
        titleVi: 'Cách di chuyển',
        titleZh: '出行方式',
        icon: Icons.directions_bus_rounded,
        background: _coralWash,
        foreground: _coral,
        completed: 0,
        total: 3,
        imagePath: 'assets/images/topics/city-travel-11-12.jpg',
      ),
      ListeningTopic(
        titleVi: 'Thói quen lành mạnh',
        titleZh: '健康习惯',
        icon: Icons.health_and_safety_rounded,
        background: _greenWash,
        foreground: _green,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/my-health-8-10.jpg',
      ),
      ListeningTopic(
        titleVi: 'An toàn trên mạng',
        titleZh: '网络安全',
        icon: Icons.shield_rounded,
        background: _blueWash,
        foreground: _blue,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/online-learning-messaging.jpg',
      ),
      ListeningTopic(
        titleVi: 'Lập kế hoạch',
        titleZh: '制定计划',
        icon: Icons.event_note_rounded,
        background: _purpleWash,
        foreground: _indigo,
        completed: 0,
        total: 3,
        imagePath: 'assets/images/topics/weekend-plans.jpg',
      ),
      ListeningTopic(
        titleVi: 'Ở cửa hàng',
        titleZh: '在商店',
        icon: Icons.storefront_rounded,
        background: _orangeWash,
        foreground: _orange,
        completed: 0,
        total: 3,
        imagePath: 'assets/images/topics/shopping-services-11-12.jpg',
      ),
      ListeningTopic(
        titleVi: 'Những vấn đề nhỏ',
        titleZh: '小问题',
        icon: Icons.help_outline_rounded,
        background: _amberWash,
        foreground: _amber,
        completed: 0,
        total: 3,
        imagePath: 'assets/images/topics/hotel-problems.jpg',
      ),
      ListeningTopic(
        titleVi: 'Hành động xanh',
        titleZh: '绿色行动',
        icon: Icons.eco_rounded,
        background: _greenWash,
        foreground: _green,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/culture-future.jpg',
      ),
    ],
  ),
  ListeningAgeCatalog(
    startAge: 13,
    endAge: 15,
    continueTopicIndex: 0,
    topics: <ListeningTopic>[
      ListeningTopic(
        titleVi: 'Sắp xếp thời gian',
        titleZh: '时间规划',
        icon: Icons.schedule_rounded,
        background: _purpleWash,
        foreground: _indigo,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/numbers-time.jpg',
      ),
      ListeningTopic(
        titleVi: 'Mục tiêu học tập',
        titleZh: '学习目标',
        icon: Icons.flag_rounded,
        background: _blueWash,
        foreground: _blue,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/study-goals.jpg',
      ),
      ListeningTopic(
        titleVi: 'Nêu ý kiến',
        titleZh: '表达观点',
        icon: Icons.record_voice_over_rounded,
        background: _greenWash,
        foreground: _green,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/express-opinions.jpg',
      ),
      ListeningTopic(
        titleVi: 'Chi tiêu thông minh',
        titleZh: '精明消费',
        icon: Icons.payments_rounded,
        background: _coralWash,
        foreground: _coral,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/shopping-services-11-12.jpg',
      ),
      ListeningTopic(
        titleVi: 'Khi cảm thấy căng thẳng',
        titleZh: '感到压力时',
        icon: Icons.sentiment_dissatisfied_rounded,
        background: _purpleWash,
        foreground: _indigo,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/feelings-opinions-11-12.jpg',
      ),
      ListeningTopic(
        titleVi: 'Quyền riêng tư trên mạng',
        titleZh: '网络隐私',
        icon: Icons.privacy_tip_rounded,
        background: _blueWash,
        foreground: _blue,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/online-learning-messaging.jpg',
      ),
      ListeningTopic(
        titleVi: 'Ở nhà ga',
        titleZh: '在车站',
        icon: Icons.train_rounded,
        background: _orangeWash,
        foreground: _orange,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/transport-directions.jpg',
      ),
      ListeningTopic(
        titleVi: 'Ở nhà hàng',
        titleZh: '在餐厅',
        icon: Icons.restaurant_menu_rounded,
        background: _amberWash,
        foreground: _amber,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/restaurant-ordering-11-12.jpg',
      ),
      ListeningTopic(
        titleVi: 'Chọn giữa hai phương án',
        titleZh: '两种选择之间',
        icon: Icons.compare_arrows_rounded,
        background: _greenWash,
        foreground: _green,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/experiences-plans-11-12.jpg',
      ),
      ListeningTopic(
        titleVi: 'Kế hoạch tương lai',
        titleZh: '未来计划',
        icon: Icons.public_rounded,
        background: _purpleWash,
        foreground: _indigo,
        completed: 0,
        total: 2,
        imagePath: 'assets/images/topics/culture-future.jpg',
      ),
    ],
  ),
];
