import 'package:flutter/material.dart';

@immutable
class ListeningTopic {
  const ListeningTopic({
    required this.titleVi,
    required this.titleZh,
    required this.icon,
    required this.background,
    required this.foreground,
    required this.completed,
    this.total = 10,
    this.imagePath,
  });

  final String titleVi;
  final String titleZh;
  final IconData icon;
  final Color background;
  final Color foreground;
  final int completed;
  final int total;
  final String? imagePath;
}

@immutable
class ListeningAgeCatalog {
  const ListeningAgeCatalog({
    required this.startAge,
    required this.endAge,
    required this.topics,
    required this.continueTopicIndex,
  });

  final int startAge;
  final int endAge;
  final List<ListeningTopic> topics;
  final int continueTopicIndex;

  String get id => '$startAge-$endAge';
}

const _indigo = Color(0xFF3D4DD6);
const _blue = Color(0xFF2684D9);
const _green = Color(0xFF23A05A);
const _orange = Color(0xFFE36A3D);
const _amber = Color(0xFFE28A21);
const _coral = Color(0xFFF36B5F);
const _purpleWash = Color(0xFFF1EEFF);
const _blueWash = Color(0xFFE9F5FF);
const _greenWash = Color(0xFFEAF7EE);
const _orangeWash = Color(0xFFFFF0E4);
const _amberWash = Color(0xFFFFF4DF);
const _coralWash = Color(0xFFFFECE7);

const listeningCatalogs = <ListeningAgeCatalog>[
  ListeningAgeCatalog(
    startAge: 3,
    endAge: 5,
    continueTopicIndex: 0,
    topics: <ListeningTopic>[
      ListeningTopic(
        titleVi: 'Xin chào và tạm biệt',
        titleZh: '问候与告别',
        icon: Icons.waving_hand_rounded,
        background: _purpleWash,
        foreground: _indigo,
        completed: 2,
        imagePath: 'assets/images/topics/hello-goodbye.jpg',
      ),
      ListeningTopic(
        titleVi: 'Bảng chữ cái vui nhộn',
        titleZh: '趣味字母表',
        icon: Icons.abc_rounded,
        background: _blueWash,
        foreground: _blue,
        completed: 1,
        imagePath: 'assets/images/topics/fun-alphabet.jpg',
      ),
      ListeningTopic(
        titleVi: 'Số đếm từ 1 đến 10',
        titleZh: '数字 1 到 10',
        icon: Icons.pin_rounded,
        background: _amberWash,
        foreground: _amber,
        completed: 0,
        imagePath: 'assets/images/topics/counting-1-10.jpg',
      ),
      ListeningTopic(
        titleVi: 'Màu sắc và hình dạng',
        titleZh: '颜色与形状',
        icon: Icons.category_rounded,
        background: _coralWash,
        foreground: _coral,
        completed: 0,
        imagePath: 'assets/images/topics/colors-shapes.jpg',
      ),
      ListeningTopic(
        titleVi: 'Gia đình của con',
        titleZh: '我的家人',
        icon: Icons.family_restroom_rounded,
        background: _orangeWash,
        foreground: _orange,
        completed: 0,
        imagePath: 'assets/images/topics/my-family.jpg',
      ),
      ListeningTopic(
        titleVi: 'Cơ thể của con',
        titleZh: '我的身体',
        icon: Icons.accessibility_new_rounded,
        background: _greenWash,
        foreground: _green,
        completed: 0,
        imagePath: 'assets/images/topics/my-body.jpg',
      ),
      ListeningTopic(
        titleVi: 'Những con vật đáng yêu',
        titleZh: '可爱的动物',
        icon: Icons.pets_rounded,
        background: _purpleWash,
        foreground: _indigo,
        completed: 0,
        imagePath: 'assets/images/topics/cute-animals.jpg',
      ),
      ListeningTopic(
        titleVi: 'Đồ ăn và thức uống',
        titleZh: '食物与饮料',
        icon: Icons.restaurant_rounded,
        background: _orangeWash,
        foreground: _orange,
        completed: 0,
        imagePath: 'assets/images/topics/food-drinks-3-5.jpg',
      ),
      ListeningTopic(
        titleVi: 'Đồ chơi của con',
        titleZh: '我的玩具',
        icon: Icons.toys_rounded,
        background: _blueWash,
        foreground: _blue,
        completed: 0,
        imagePath: 'assets/images/topics/my-toys.jpg',
      ),
      ListeningTopic(
        titleVi: 'Hành động và cảm xúc',
        titleZh: '动作与情绪',
        icon: Icons.sentiment_satisfied_alt_rounded,
        background: _greenWash,
        foreground: _green,
        completed: 0,
        imagePath: 'assets/images/topics/actions-emotions.jpg',
      ),
    ],
  ),
  ListeningAgeCatalog(
    startAge: 6,
    endAge: 7,
    continueTopicIndex: 3,
    topics: <ListeningTopic>[
      ListeningTopic(
        titleVi: 'Tên và tuổi của con',
        titleZh: '姓名和年龄',
        icon: Icons.waving_hand_rounded,
        background: _purpleWash,
        foreground: _indigo,
        completed: 6,
        imagePath: 'assets/images/topics/name-age.jpg',
      ),
      ListeningTopic(
        titleVi: 'Gia đình và ngôi nhà',
        titleZh: '家庭和住宅',
        icon: Icons.home_rounded,
        background: _orangeWash,
        foreground: _orange,
        completed: 4,
        imagePath: 'assets/images/topics/family-home.jpg',
      ),
      ListeningTopic(
        titleVi: 'Cặp sách và lớp học',
        titleZh: '书包和教室',
        icon: Icons.school_rounded,
        background: _blueWash,
        foreground: _blue,
        completed: 3,
        imagePath: 'assets/images/topics/school-bag.jpg',
      ),
      ListeningTopic(
        titleVi: 'Một ngày ở trường',
        titleZh: '学校的一天',
        icon: Icons.account_balance_rounded,
        background: _greenWash,
        foreground: _green,
        completed: 2,
        imagePath: 'assets/images/topics/school-day.jpg',
      ),
      ListeningTopic(
        titleVi: 'Số đếm',
        titleZh: '数字、日期和时间',
        icon: Icons.schedule_rounded,
        background: _amberWash,
        foreground: _amber,
        completed: 1,
        imagePath: 'assets/images/topics/numbers-time.jpg',
      ),
      ListeningTopic(
        titleVi: 'Đồ ăn con thích',
        titleZh: '喜欢的食物',
        icon: Icons.lunch_dining_rounded,
        background: _coralWash,
        foreground: _coral,
        completed: 2,
        imagePath: 'assets/images/topics/favorite-food.jpg',
      ),
      ListeningTopic(
        titleVi: 'Một ngày của con',
        titleZh: '日常活动',
        icon: Icons.directions_run_rounded,
        background: _purpleWash,
        foreground: _indigo,
        completed: 0,
        imagePath: 'assets/images/topics/daily-activities-6-7.jpg',
      ),
      ListeningTopic(
        titleVi: 'Thời tiết',
        titleZh: '天气和衣服',
        icon: Icons.wb_sunny_rounded,
        background: _amberWash,
        foreground: _amber,
        completed: 0,
        imagePath: 'assets/images/topics/weather-clothes-6-7.jpg',
      ),
      ListeningTopic(
        titleVi: 'Sở thích và thể thao',
        titleZh: '爱好和运动',
        icon: Icons.sports_soccer_rounded,
        background: _greenWash,
        foreground: _green,
        completed: 0,
        imagePath: 'assets/images/topics/hobbies-sports-6-7.jpg',
      ),
      ListeningTopic(
        titleVi: 'Lời nói lịch sự và nhu cầu',
        titleZh: '礼貌用语和简单需求',
        icon: Icons.volunteer_activism_rounded,
        background: _coralWash,
        foreground: _coral,
        completed: 0,
        imagePath: 'assets/images/topics/polite-needs-6-7.jpg',
      ),
    ],
  ),
  ListeningAgeCatalog(
    startAge: 8,
    endAge: 10,
    continueTopicIndex: 1,
    topics: <ListeningTopic>[
      ListeningTopic(
        titleVi: 'Con và những người bạn',
        titleZh: '我和朋友们',
        icon: Icons.groups_rounded,
        background: _purpleWash,
        foreground: _indigo,
        completed: 5,
        imagePath: 'assets/images/topics/friends-8-10.jpg',
      ),
      ListeningTopic(
        titleVi: 'Môn học và thời khóa biểu',
        titleZh: '科目和课程表',
        icon: Icons.calendar_month_rounded,
        background: _blueWash,
        foreground: _blue,
        completed: 3,
        imagePath: 'assets/images/topics/subjects-timetable.jpg',
      ),
      ListeningTopic(
        titleVi: 'Một ngày ở trường',
        titleZh: '我的一天',
        icon: Icons.today_rounded,
        background: _amberWash,
        foreground: _amber,
        completed: 1,
        imagePath: 'assets/images/topics/my-day-8-10.jpg',
      ),
      ListeningTopic(
        titleVi: 'Môn thể thao',
        titleZh: '爱好和运动',
        icon: Icons.sports_basketball_rounded,
        background: _greenWash,
        foreground: _green,
        completed: 0,
        imagePath: 'assets/images/topics/hobbies-sports-8-10.jpg',
      ),
      ListeningTopic(
        titleVi: 'Con giúp đỡ gia đình',
        titleZh: '我帮助家人',
        icon: Icons.cleaning_services_rounded,
        background: _orangeWash,
        foreground: _orange,
        completed: 0,
        imagePath: 'assets/images/topics/help-family.jpg',
      ),
      ListeningTopic(
        titleVi: 'Đi mua sắm',
        titleZh: '购物',
        icon: Icons.shopping_bag_rounded,
        background: _coralWash,
        foreground: _coral,
        completed: 0,
        imagePath: 'assets/images/topics/shopping-8-10.jpg',
      ),
      ListeningTopic(
        titleVi: 'Đi ăn uống',
        titleZh: '外出就餐',
        icon: Icons.restaurant_menu_rounded,
        background: _orangeWash,
        foreground: _orange,
        completed: 0,
        imagePath: 'assets/images/topics/eating-out-8-10.jpg',
      ),
      ListeningTopic(
        titleVi: 'Sức khỏe của con',
        titleZh: '我的健康',
        icon: Icons.health_and_safety_rounded,
        background: _greenWash,
        foreground: _green,
        completed: 0,
        imagePath: 'assets/images/topics/my-health-8-10.jpg',
      ),
      ListeningTopic(
        titleVi: 'Phương tiện và hỏi đường',
        titleZh: '交通和问路',
        icon: Icons.directions_bus_rounded,
        background: _blueWash,
        foreground: _blue,
        completed: 0,
        imagePath: 'assets/images/topics/transport-directions.jpg',
      ),
      ListeningTopic(
        titleVi: 'Kế hoạch cuối tuần',
        titleZh: '周末计划',
        icon: Icons.weekend_rounded,
        background: _purpleWash,
        foreground: _indigo,
        completed: 0,
        imagePath: 'assets/images/topics/weekend-plans.jpg',
      ),
    ],
  ),
  ListeningAgeCatalog(
    startAge: 11,
    endAge: 12,
    continueTopicIndex: 3,
    topics: <ListeningTopic>[
      ListeningTopic(
        titleVi: 'Làm quen bạn mới',
        titleZh: '认识新朋友',
        icon: Icons.person_add_alt_1_rounded,
        background: _purpleWash,
        foreground: _indigo,
        completed: 4,
        imagePath: 'assets/images/topics/new-friends-11-12.jpg',
      ),
      ListeningTopic(
        titleVi: 'Cuộc sống và việc học ở trường',
        titleZh: '学校生活与学习',
        icon: Icons.school_rounded,
        background: _blueWash,
        foreground: _blue,
        completed: 3,
        imagePath: 'assets/images/topics/school-life-11-12.jpg',
      ),
      ListeningTopic(
        titleVi: 'Câu lạc bộ và làm việc nhóm',
        titleZh: '社团与团队合作',
        icon: Icons.diversity_3_rounded,
        background: _greenWash,
        foreground: _green,
        completed: 2,
        imagePath: 'assets/images/topics/clubs-teamwork-11-12.jpg',
      ),
      ListeningTopic(
        titleVi: 'Cảm xúc và ý kiến của con',
        titleZh: '我的情绪与观点',
        icon: Icons.forum_rounded,
        background: _coralWash,
        foreground: _coral,
        completed: 1,
        imagePath: 'assets/images/topics/feelings-opinions-11-12.jpg',
      ),
      ListeningTopic(
        titleVi: 'Điện thoại và Internet',
        titleZh: '手机和互联网',
        icon: Icons.language_rounded,
        background: _purpleWash,
        foreground: _indigo,
        completed: 0,
        imagePath: 'assets/images/topics/phone-internet-11-12.jpg',
      ),
      ListeningTopic(
        titleVi: 'Mua sắm và dịch vụ',
        titleZh: '购物和服务',
        icon: Icons.storefront_rounded,
        background: _orangeWash,
        foreground: _orange,
        completed: 0,
        imagePath: 'assets/images/topics/shopping-services-11-12.jpg',
      ),
      ListeningTopic(
        titleVi: 'Nhà hàng và gọi món',
        titleZh: '餐厅和点餐',
        icon: Icons.ramen_dining_rounded,
        background: _amberWash,
        foreground: _amber,
        completed: 0,
        imagePath: 'assets/images/topics/restaurant-ordering-11-12.jpg',
      ),
      ListeningTopic(
        titleVi: 'Sức khỏe và nhờ giúp đỡ',
        titleZh: '健康与求助',
        icon: Icons.medical_services_rounded,
        background: _greenWash,
        foreground: _green,
        completed: 0,
        imagePath: 'assets/images/topics/health-help-11-12.jpg',
      ),
      ListeningTopic(
        titleVi: 'Đi lại trong thành phố',
        titleZh: '城市出行',
        icon: Icons.map_rounded,
        background: _blueWash,
        foreground: _blue,
        completed: 0,
        imagePath: 'assets/images/topics/city-travel-11-12.jpg',
      ),
      ListeningTopic(
        titleVi: 'Trải nghiệm và kế hoạch',
        titleZh: '经历与计划',
        icon: Icons.route_rounded,
        background: _purpleWash,
        foreground: _indigo,
        completed: 0,
        imagePath: 'assets/images/topics/experiences-plans-11-12.jpg',
      ),
    ],
  ),
  ListeningAgeCatalog(
    startAge: 13,
    endAge: 15,
    continueTopicIndex: 1,
    topics: <ListeningTopic>[
      ListeningTopic(
        titleVi: 'Giới thiệu bản thân chi tiết',
        titleZh: '详细自我介绍',
        icon: Icons.badge_rounded,
        background: _purpleWash,
        foreground: _indigo,
        completed: 4,
        imagePath: 'assets/images/topics/detailed-introduction.jpg',
      ),
      ListeningTopic(
        titleVi: 'Học tập và mục tiêu cá nhân',
        titleZh: '学习与个人目标',
        icon: Icons.flag_rounded,
        background: _blueWash,
        foreground: _blue,
        completed: 2,
        imagePath: 'assets/images/topics/study-goals.jpg',
      ),
      ListeningTopic(
        titleVi: 'Bạn bè và giao tiếp xã hội',
        titleZh: '朋友与社交',
        icon: Icons.people_alt_rounded,
        background: _greenWash,
        foreground: _green,
        completed: 1,
        imagePath: 'assets/images/topics/friends-social.jpg',
      ),
      ListeningTopic(
        titleVi: 'Bày tỏ và bảo vệ ý kiến',
        titleZh: '表达和维护观点',
        icon: Icons.record_voice_over_rounded,
        background: _coralWash,
        foreground: _coral,
        completed: 0,
        imagePath: 'assets/images/topics/express-opinions.jpg',
      ),
      ListeningTopic(
        titleVi: 'Làm việc nhóm và thuyết trình',
        titleZh: '团队合作与演讲',
        icon: Icons.co_present_rounded,
        background: _purpleWash,
        foreground: _indigo,
        completed: 0,
        imagePath: 'assets/images/topics/teamwork-presentation.jpg',
      ),
      ListeningTopic(
        titleVi: 'Học trực tuyến và nhắn tin',
        titleZh: '在线学习与消息沟通',
        icon: Icons.devices_rounded,
        background: _blueWash,
        foreground: _blue,
        completed: 0,
        imagePath: 'assets/images/topics/online-learning-messaging.jpg',
      ),
      ListeningTopic(
        titleVi: 'Lập kế hoạch chuyến đi',
        titleZh: '制定旅行计划',
        icon: Icons.luggage_rounded,
        background: _orangeWash,
        foreground: _orange,
        completed: 0,
        imagePath: 'assets/images/topics/trip-planning.jpg',
      ),
      ListeningTopic(
        titleVi: 'Sân bay và chuyến bay',
        titleZh: '机场与航班',
        icon: Icons.flight_takeoff_rounded,
        background: _amberWash,
        foreground: _amber,
        completed: 0,
        imagePath: 'assets/images/topics/airport-flights.jpg',
      ),
      ListeningTopic(
        titleVi: 'Khách sạn và xử lý vấn đề',
        titleZh: '酒店与问题处理',
        icon: Icons.hotel_rounded,
        background: _greenWash,
        foreground: _green,
        completed: 0,
        imagePath: 'assets/images/topics/hotel-problems.jpg',
      ),
      ListeningTopic(
        titleVi: 'Văn hóa, du học và tương lai',
        titleZh: '文化、留学与未来',
        icon: Icons.public_rounded,
        background: _purpleWash,
        foreground: _indigo,
        completed: 0,
        imagePath: 'assets/images/topics/culture-future.jpg',
      ),
    ],
  ),
];
