// GENERATED CODE - DO NOT MODIFY BY HAND.
// Source: HOMI_Danh_muc_cau_thoai_AI_Fallback_Kho_500_cau_Gui_IT.xlsx
// Regenerate with: python tool/generate_homi_fallback_catalog.py

class HomiNumericPhrasePattern {
  const HomiNumericPhrasePattern({
    required this.raw,
    required this.literalSegments,
    required this.placeholderNames,
  });

  final String raw;
  final List<String> literalSegments;
  final List<String> placeholderNames;
}

class HomiFallbackPolicy {
  const HomiFallbackPolicy({
    required this.id,
    required this.context,
    required this.condition,
    required this.behavior,
    required this.exampleChildUtterance,
    required this.firstPrompt,
    required this.firstAction,
    required this.secondPrompt,
    required this.finalAction,
    required this.priority,
    required this.status,
  });

  final String id;
  final String context;
  final String condition;
  final String behavior;
  final String exampleChildUtterance;
  final String firstPrompt;
  final String firstAction;
  final String secondPrompt;
  final String finalAction;
  final String priority;
  final String status;
}

/// Dependency-free, synchronous copy of the approved HOMI corpus.
class HomiFallbackCatalog {
  const HomiFallbackCatalog._();

  static const int literalChildPhraseCount = 488;
  static const int numericChildTemplateCount = 12;

  /// Literal phrases only. Numeric bracket templates remain separate so
  /// callers activate them only while a number is expected.
  static const Map<String, List<String>> childPhrasesByIntent =
      <String, List<String>>{
        'INT-001': <String>[
          'Dừng lại',
          'Dừng',
          'Thôi',
          'Không học nữa',
          'Tạm dừng',
          'Stop',
          'Dừng đi',
          'Thôi nha',
          'Không muốn nữa',
          'Mình không thích',
          'Im lặng',
          'Mình muốn nghỉ',
          'Mình muốn dừng',
          'Mình nghỉ một chút',
          'Dừng giúp mình',
          'Thôi mình nghỉ',
          'Mình không muốn học nữa đâu',
          'Nghỉ tí đi',
          'Cho mình nghỉ đi',
          'Mình nghỉ nha',
          'Mình hông muốn học nữa',
          'Mình hổng muốn học nữa',
          'Thôi, mình nghỉ nghen',
          'Mình nghỉ đây',
          'Cho mình dừng một chút',
          'Mình muốn tạm nghỉ',
          'Thôi, dừng ở đây nha',
        ],
        'INT-002': <String>[
          'Học theo chủ đề',
          'Bắt đầu học',
          'Mình muốn học',
          'Học chủ đề',
          'Học tình huống',
          'Mình muốn học theo Chủ đề',
          'Học đi',
          'Mình học',
          'Học cái này',
          'Học bây giờ',
          'Chủ đề',
          'Mình muốn học bài',
          'Cho mình học bài',
          'Học bài đi',
          'Mình muốn học bài này',
          'Cho mình học chủ đề này',
          'Mình muốn vào học',
          'Cho mình học đi',
          'Mình muốn học nè',
          'Cho mình vô học',
          'Mình học cái này nè',
          'Học bài ni',
          'Mình muốn học cái ni',
          'Mình muốn học chủ đề này',
          'Cho mình vào bài học',
          'Mình học bài này nha',
          'Bắt đầu chủ đề này đi',
        ],
        'INT-003': <String>[
          'Học từ mới',
          'Mình muốn học từ',
          'Học từ vựng',
          'Luyện từ mới',
          'Từ mới',
          'Học từ',
          'Học mới',
          'Từ vựng',
          'Mình muốn học từ mới',
          'Cho mình học từ mới',
          'Học mấy từ mới',
          'Mình muốn học các từ mới',
          'Học chữ mới',
          'Mình học chữ',
          'Cho mình học chữ mới',
          'Học từ đi',
          'Tớ muốn học từ mới',
          'Học mấy chữ này nè',
          'Mình muốn học chữ nè',
          'Học chữ ni',
          'Mình muốn học chữ mới',
          'Cho mình học mấy từ mới',
          'Học thêm từ mới nha',
          'Mình muốn học từ vựng',
        ],
        'INT-004': <String>[
          'Dịch tiếng Anh',
          'Dịch',
          'Mình muốn dịch',
          'Dịch giúp mình',
          'Dịch tiếng Anh',
          'Dịch cho mình',
          'Dịch đi',
          'Mình muốn nói tiếng Anh',
          'Dịch câu này',
          'Dịch cái này',
          'Dịch từ này',
          'Dịch cho mình sang tiếng Anh',
          'Mình muốn dịch câu này sang tiếng Anh',
          'Bạn dịch cái này sang tiếng Anh giúp mình',
          'Nói tiếng Anh giúp mình',
          'Dịch cái này ra tiếng Anh',
          'Dịch câu này sang tiếng Anh giúp mình',
          'Cậu dịch sang tiếng Anh giúp tớ',
          'Bạn dịch câu này sang tiếng Anh giúp tớ',
          'Dịch qua tiếng Anh giùm mình',
          'Nói tiếng Anh',
          'Tiếng Anh',
          'Cái ni tiếng Anh',
          'Câu ni tiếng Anh',
          'Bạn dịch sang tiếng Anh giúp mình',
          'Mình muốn dịch sang tiếng Anh',
          'Dịch câu này sang tiếng Anh đi',
          'Bạn giúp mình nói câu này bằng tiếng Anh',
          'Mở phần dịch tiếng Anh giúp mình',
        ],
        'INT-006': <String>[
          'Dịch liên tục',
          'Dịch nhiều',
          'Dịch liên tiếp',
          'Dịch tiếp đi',
          'Mình nói liên tục',
          'Dịch hoài',
          'Dịch nhiều câu',
          'Dịch tiếp',
          'Nói tiếp',
          'Dịch liên tục cho mình',
          'Mình muốn dịch nhiều câu',
          'Dịch từng câu liên tiếp',
          'Dịch quài luôn',
          'Dịch hết mấy câu mình nói',
          'Dịch tiếp nhiều câu',
          'Cậu bật dịch liên tục giúp tớ',
          'Mở chế độ dịch liên tục giúp mình',
          'Mình muốn dịch quài quài luôn',
          'Dịch tiếp nghen',
          'Cho mình bật dịch liên tục',
          'Dịch liên tiếp giúp mình',
          'Mình muốn dịch nhiều câu liền',
          'Dịch nhiều câu luôn nha',
        ],
        'INT-007': <String>[
          'Tiếp tục học',
          'Học tiếp',
          'Tiếp tục bài này',
          'Học tiếp đi',
          'Mình muốn học nữa',
          'Mình học nữa',
          'Học tiếp bài này',
          'Tiếp tục đi',
          'Học nữa đi',
          'Mình muốn tiếp tục',
          'Cho mình học tiếp',
          'Mình học nữa',
          'Tớ muốn học tiếp',
          'Học tiếp nha bạn',
          'Học tiếp bài ni',
          'Mình muốn học tiếp',
          'Cho mình tiếp tục bài này',
          'Học tiếp nha bạn',
        ],
        'INT-008': <String>[
          'Câu tiếp theo',
          'Qua câu tiếp',
          'Câu sau',
          'Nói câu khác',
          'Câu nữa',
          'Tiếp đi',
          'Câu tiếp',
          'Sang câu tiếp theo',
          'Qua câu sau',
          'Cho mình câu tiếp',
          'Câu kế tiếp',
          'Câu kế',
          'Tiếp câu khác',
          'Đổi câu đi',
          'Cho mình câu khác',
          'Câu sau đi',
          'Sang câu mới',
          'Cậu cho tớ câu tiếp theo',
          'Qua câu kế',
          'Cho mình sang câu sau',
          'Qua câu kế đi',
          'Mình muốn câu tiếp theo',
        ],
        'INT-009': <String>[
          'Câu trước',
          'Quay lại câu trước',
          'Lùi một câu',
          'Câu hồi nãy',
          'Quay lại',
          'Về trước',
          'Về câu trước',
          'Cho mình câu trước',
          'Quay lại câu vừa rồi',
          'Câu vừa nãy',
          'Câu lúc nãy',
          'Câu ban nãy',
          'Lùi lại',
          'Quay lại một câu',
          'Về câu cũ',
          'Quay lại câu nãy nha',
          'Tớ muốn quay lại câu trước',
          'Cho mình quay lại câu trước',
          'Về câu vừa rồi nha',
          'Mình muốn về câu trước',
        ],
        'INT-010': <String>[
          'Nghe lại',
          'Nói lại',
          'Đọc lại câu này',
          'Cho mình nghe lại',
          'Nghe nữa',
          'Nói lại đi',
          'Lặp lại',
          'Lần nữa',
          'Nghe lại câu này',
          'Cho mình nghe lại câu này',
          'Mở lại câu này',
          'Phát lại đi',
          'Phát lại câu này',
          'Nghe lại một lần',
          'Nghe thêm lần nữa',
          'Bạn nói lại câu này',
          'Nói lại cho mình nghe',
          'Cậu nói lại cho tớ nghe',
          'Nói lại nha bạn',
          'Nghe lại câu ni',
          'Bạn phát lại câu này đi',
          'Mình muốn nghe lại lần nữa',
          'Bạn nói lại cho mình nghe nha',
        ],
        'INT-011': <String>[
          'Học lại từ đầu',
          'Học từ đầu',
          'Làm lại bài này',
          'Học lại',
          'Lại từ đầu',
          'Làm lại từ đầu',
          'Mình muốn học lại từ đầu',
          'Bắt đầu lại từ đầu',
          'Học lại cả bài',
          'Cho mình học lại bài',
          'Làm lại bài từ đầu',
          'Học lại bài này từ đầu',
          'Quay về đầu bài',
          'Bắt đầu lại bài này',
          'Cho mình làm lại từ đầu với',
          'Học lại bài này nha',
          'Học lại bài ni từ đầu',
          'Mình muốn làm lại từ đầu',
          'Cho mình bắt đầu lại bài này',
          'Học lại từ câu đầu đi',
        ],
        'INT-012': <String>[
          'Bài tiếp theo',
          'Qua bài mới',
          'Bài sau',
          'Bài tiếp',
          'Bài nữa',
          'Học bài khác',
          'Bài mới',
          'Sang bài tiếp theo',
          'Qua bài sau',
          'Cho mình bài tiếp',
          'Bài kế tiếp',
          'Học bài sau',
          'Chuyển bài sau',
          'Qua bài tiếp',
          'Cho mình học bài mới',
          'Cậu cho tớ sang bài tiếp theo',
          'Qua bài kế',
          'Bài kế nha',
          'Cho mình sang bài sau',
          'Mình muốn học bài tiếp',
          'Qua bài kế nha',
        ],
        'INT-013': <String>[
          'Bài trước',
          'Quay lại bài trước',
          'Bài hồi nãy',
          'Bài trước đó',
          'Quay lại bài cũ',
          'Bài lúc nãy',
          'Sang bài trước',
          'Về bài trước',
          'Cho mình bài trước',
          'Quay lại bài vừa rồi',
          'Bài vừa nãy',
          'Bài ban nãy',
          'Về bài cũ',
          'Quay lại một bài',
          'Bạn cho tớ quay lại bài trước',
          'Quay lại bài nãy nha',
          'Về bài trước nha',
          'Cho mình về bài trước',
          'Mình muốn quay lại bài cũ',
          'Mở lại bài trước đi',
        ],
        'INT-014': <String>[
          'Luyện lại',
          'Học lại phần chưa thuộc',
          'Luyện từ khó',
          'Nói lại',
          'Học lại',
          'Mấy câu khó',
          'Luyện nữa',
          'Mình muốn luyện lại',
          'Cho mình luyện lại',
          'Luyện mấy từ mình chưa thuộc',
          'Học lại mấy từ khó',
          'Ôn lại từ khó',
          'Ôn lại mấy từ này',
          'Luyện thêm',
          'Mình muốn ôn lại',
          'Học lại từ chưa nhớ',
          'Luyện lại mấy chữ',
          'Bạn cho tớ ôn lại',
          'Ôn lại mấy chữ này nè',
          'Luyện mấy chữ ni',
          'Mình muốn ôn mấy từ khó',
          'Cho mình luyện lại mấy từ khó',
          'Ôn lại phần chưa nhớ nha',
        ],
        'INT-015': <String>[
          'Ngôi sao của mình',
          'Xem ngôi sao',
          'Học phần ngôi sao',
          'Ngôi sao',
          'Mình học ngôi sao',
          'Xem sao',
          'Muốn ngôi sao',
          'Nhìn ngôi sao',
          'Cho mình xem sao',
          'Mình muốn xem ngôi sao',
          'Xem sao của mình',
          'Mình xem phần ngôi sao',
          'Cho mình xem mình được mấy sao',
          'Xem phần mình đã học được',
          'Mở ngôi sao cho mình',
          'Cậu cho tớ xem ngôi sao',
          'Mình muốn coi sao',
          'Coi ngôi sao',
          'Cho mình coi sao với',
          'Cho mình xem ngôi sao',
          'Tớ muốn xem ngôi sao của mình',
          'Mở phần ngôi sao đi',
        ],
        'INT-016': <String>[
          'Giúp mình với',
          'Mình không biết',
          'Phải làm gì?',
          'Nói lại đi',
          'Giúp',
          'Giúp mình',
          'Không biết',
          'Không hiểu',
          'Sao đây?',
          'Nói gì?',
          'Bạn giúp mình',
          'Giúp mình đi',
          'Mình phải làm sao?',
          'Giờ làm gì?',
          'Tiếp theo làm gì?',
          'Mình chưa biết làm',
          'Chỉ mình với',
          'Bạn chỉ mình đi',
          'Làm sao bây giờ?',
          'Cậu giúp tớ với',
          'Bạn chỉ tớ với',
          'Mình làm sao giờ?',
          'Giờ mình làm cái chi?',
          'Bạn giúp mình đi mà',
          'Mình chưa biết làm gì',
          'Bạn chỉ mình với',
        ],
        'INT-017': <String>[
          'Mình muốn học cái khác',
          'Cái gì khác để học',
          'Gì khác để học',
          'Có gì khác không',
          'Học thử cái khác',
          'Học môn khác',
          'Học bài khác',
          'Đổi sang học cái khác',
          'Mình muốn chuyển sang học cái khác',
          'Đổi sang phần khác giúp mình',
          'Mình muốn làm cái khác',
          'Đổi cái khác đi',
          'Cho mình học cái khác',
          'Chuyển sang chức năng khác đi',
          'Mình muốn đổi bài',
          'Đổi sang phần khác',
          'Mình muốn học phần khác',
          'Học cái khác nha',
          'Qua cái khác đi',
          'Đổi qua cái khác đi',
          'Cho mình đổi cái khác với',
          'Mình muốn học thứ khác',
          'Mình muốn chuyển sang cái khác',
          'Cho mình đổi sang phần khác',
          'Mình muốn thử chức năng khác',
          'Đổi qua cái khác nha',
        ],
        'INT-018': <String>[
          'Dừng lại',
          'Mình muốn dừng',
          'Dừng dịch',
          'Dừng dịch liên tục',
          'Ngừng',
          'Mình muốn ngừng',
          'Ngừng dịch',
          'Thôi dừng lại',
          'Không dịch nữa',
          'Mình không muốn dịch nữa',
          'Thoát dịch',
          'Dừng dịch đi',
          'Thôi dịch',
          'Mình không dịch nữa',
          'Nghỉ dịch',
          'Dừng phần dịch',
          'Thoát phần dịch',
          'Không dịch nữa đâu',
          'Thôi không dịch nữa',
          'Dừng dịch giúp mình',
          'Tớ không muốn dịch nữa',
          'Dừng',
          'Hổng dịch nữa',
          'Mình hông muốn dịch nữa',
          'Mình muốn dừng dịch',
          'Thôi, không dịch nữa đâu',
          'Dừng phần dịch giúp mình',
          'Mình nghỉ dịch nha',
        ],
        'INT-019': <String>[
          'Có',
          'Ừ, học lại',
          'Ừa, tớ muốn học lại',
          'Mình có',
          'Muốn học lại',
          'Học lại',
          'Ừ, mình muốn học lại',
          'OK, được',
          'Ừ',
          'Được luôn',
          'Ừ, tớ muốn',
          'Tớ đồng ý học lại',
          'OK',
          'Cậu cho tớ học lại bài này',
          'Ừa, mình học lại',
          'Có chứ',
          'Mình muốn',
          'Mình muốn học lại',
          'Oki luôn',
          'Có nè',
          'Ừm',
          'Ừ, mình muốn',
          'OK, học lại luôn',
          'Ừ, học lại đi',
        ],
        'INT-020': <String>[
          'Không',
          'Không muốn học lại',
          'Nô, tớ không muốn',
          'Mình không',
          'Không đâu',
          'Không muốn',
          'Không học',
          'Thôi, mình không học lại',
          'Thôi, không học lại',
          'Tớ không học lại',
          'Không cần',
          'Không cần đâu',
          'Mình thôi',
          'Thôi mình không học',
          'Mình muốn nghỉ rồi',
          'Hông',
          'Hông, mình không muốn',
          'Hổng',
          'Mình hổng muốn',
          'Mình không muốn học lại',
          'Thôi, bỏ qua đi',
          'Không học lại đâu',
        ],
        'INT-021': <String>[
          'Một đến mười lăm',
          '1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15 và dạng chữ tiếng Việt',
          'Bốn / Tư',
          'Mười bốn / Mười tư',
          'Mười một / Mười mốt',
        ],
        'INT-022': <String>[
          'Hey HOMI',
          'Hey HÔMI',
          'Hey HAMI',
          'Hay HOMIE',
          'Hey HOMY',
          'Hay HÔMY',
          'Hey HO MI',
          'Hay HO MIE',
          'Hey HOMY',
          'Hay HA MI',
          'Hey HIMI',
          'Hay HUMI',
          'Ê HOMPI',
          'Ê HOM ĐI',
          'HOMI ơi',
          'Bạn HOMI ơi',
          'Ê HOMI',
          'Hôm-mi ơi',
          'Homi giúp mình',
          'Bạn ơi',
          'HOMI nghe mình nói không?',
          'HOMI, mình muốn nói',
          'HOMI có nghe không?',
          'HOMI, mình cần bạn',
        ],
      };

  static const Map<String, List<HomiNumericPhrasePattern>>
  numericChildPatternsByIntent = <String, List<HomiNumericPhrasePattern>>{
    'INT-021': <HomiNumericPhrasePattern>[
      HomiNumericPhrasePattern(
        raw: 'Mình [số] tuổi',
        literalSegments: <String>['Mình', 'tuổi'],
        placeholderNames: <String>['số'],
      ),
      HomiNumericPhrasePattern(
        raw: '[số] tuổi',
        literalSegments: <String>['', 'tuổi'],
        placeholderNames: <String>['số'],
      ),
      HomiNumericPhrasePattern(
        raw: 'Mình chọn [số]',
        literalSegments: <String>['Mình chọn', ''],
        placeholderNames: <String>['số'],
      ),
      HomiNumericPhrasePattern(
        raw: 'Chọn số [số]',
        literalSegments: <String>['Chọn số', ''],
        placeholderNames: <String>['số'],
      ),
      HomiNumericPhrasePattern(
        raw: 'Số [số]',
        literalSegments: <String>['Số', ''],
        placeholderNames: <String>['số'],
      ),
      HomiNumericPhrasePattern(
        raw: 'Bài số [số]',
        literalSegments: <String>['Bài số', ''],
        placeholderNames: <String>['số'],
      ),
      HomiNumericPhrasePattern(
        raw: 'Mình chọn bài thứ [số]',
        literalSegments: <String>['Mình chọn bài thứ', ''],
        placeholderNames: <String>['số'],
      ),
      HomiNumericPhrasePattern(
        raw: 'Chủ đề số [số]',
        literalSegments: <String>['Chủ đề số', ''],
        placeholderNames: <String>['số'],
      ),
      HomiNumericPhrasePattern(
        raw: 'Mình chọn chủ đề [số]',
        literalSegments: <String>['Mình chọn chủ đề', ''],
        placeholderNames: <String>['số'],
      ),
      HomiNumericPhrasePattern(
        raw: 'Mình chọn số [số]',
        literalSegments: <String>['Mình chọn số', ''],
        placeholderNames: <String>['số'],
      ),
      HomiNumericPhrasePattern(
        raw: 'Cho mình bài số [số]',
        literalSegments: <String>['Cho mình bài số', ''],
        placeholderNames: <String>['số'],
      ),
      HomiNumericPhrasePattern(
        raw: 'Mình muốn chủ đề số [số]',
        literalSegments: <String>['Mình muốn chủ đề số', ''],
        placeholderNames: <String>['số'],
      ),
    ],
  };

  static const Map<String, String> assistantPromptById = <String, String>{
    'AI-001':
        'HOMI đây. Bạn muốn dịch sang tiếng Anh, học theo chủ đề hay học bộ từ vựng?',
    'AI-002':
        'Bạn có thể chọn: dịch sang tiếng Anh, học theo chủ đề hoặc học bộ từ vựng',
    'AI-003': 'Khi sẵn sàng, bạn nhấn nút gọi HOMI nhé.',
    'AI-004':
        'Được thôi. Bạn muốn dịch sang tiếng Anh, học theo chủ đề hay học bộ từ vựng?',
    'AI-005':
        'Bạn muốn nghe lại, học câu tiếp theo, học câu trước, hay dừng lại?',
    'AI-006': 'Bạn muốn dịch sang tiếng Anh hay học bộ từ vựng?',
    'AI-007': 'Bạn mấy tuổi?',
    'AI-008': 'Bạn mấy tuổi? Ví dụ bạn nói: 6 tuổi.',
    'AI-009':
        'HOMI có bài học cho các bạn từ {tuổi nhỏ nhất} đến {tuổi lớn nhất} tuổi. Bạn mấy tuổi?',
    'AI-010': 'Có {số chủ đề} chủ đề. Bạn muốn học chủ đề số mấy?',
    'AI-011': 'Có {số chủ đề} chủ đề. Bạn chọn từ số 1 đến số {số chủ đề}.',
    'AI-012': 'Chủ đề này chưa có bài học. Bạn chọn chủ đề khác nha.',
    'AI-013': 'Có {số bài} bài học. Bạn muốn học bài số mấy?',
    'AI-014': 'Có {số bài} bài học. Bạn chọn từ số 1 đến số {số bài}.',
    'AI-015': 'Bạn đã học chủ đề số {số chủ đề} rồi. Bạn muốn học lại không?',
    'AI-016':
        'Bạn muốn học lại chủ đề số {số chủ đề} không? Nói “có” hoặc “không”.',
    'AI-017': 'Mình bắt đầu học thôi.',
    'AI-018': 'HOMI chưa tải được bài học. Bạn thử lại sau.',
    'AI-019': 'HOMI chưa chọn được chủ đề. Bạn thử lại.',
    'AI-020': 'Mình cùng dịch sang tiếng Anh nha.',
    'AI-022': 'Bạn cứ nói từng câu. Muốn dừng thì nói “dừng lại”.',
    'AI-023': 'HOMI chưa nghe thấy bạn nói. Bạn nói lại đi.',
    'AI-024': 'Mình dừng ở đây. Khi cần, bạn nhấn nút gọi HOMI.',
    'AI-025': 'HOMI chưa nghe thấy bạn nói. Bạn nói lại đi.',
    'AI-026':
        'Ở đây hơi ồn. Bạn đưa micro lại gần, tránh hướng quạt hoặc chuyển sang chỗ yên hơn rồi thử lại nhé.',
    'AI-027': 'HOMI chưa nghe rõ. Bạn thử nói lại nhé.',
    'AI-028': 'HOMI chưa tải được từ vựng. Bạn thử lại sau nha.',
    'AI-029': 'Bạn muốn luyện tập lại hay xem bộ sưu tập ngôi sao?',
    'AI-030': 'Có từ mới rồi. Mình cùng học nha.',
    'AI-031': '{từ tiếng Anh} → {nghĩa tiếng Việt}',
    'AI-032': 'Mình qua phần luyện lại và ngôi sao nha.',
    'AI-033': 'Phần luyện lại.',
    'AI-034': 'Phần luyện lại chưa có từ nào.',
    'AI-035': 'Bộ sưu tập ngôi sao.',
    'AI-036': 'Bộ sưu tập ngôi sao chưa có từ nào.',
    'AI-037': 'Mình đã học xong bộ từ vựng hôm nay rồi.',
    'AI-038': 'Mình học tiếp thôi.',
    'AI-039': 'Mình nghe lại câu này nhé.',
    'AI-040': 'Mình học câu tiếp theo thôi.',
    'AI-041': 'Mình quay lại câu trước nha.',
    'AI-042': 'Mình chuyển sang bài tiếp theo nào.',
    'AI-043': 'Mình quay lại bài trước nhé.',
    'AI-044': 'Mình học lại bài này từ đầu nha.',
    'AI-045': 'Đã dừng.',
    'AI-046': 'Mình kết thúc bài học ở đây nhé.',
    'AI-047': 'Nghe HOMI trước, rồi bạn nói lại sau nha.',
    'AI-048': 'Đến lượt bạn. Bạn nói lại đi.',
    'AI-049': 'Bạn chọn “Luyện lại từ đầu” hay “Bài tiếp theo”?',
    'AI-050': 'Bạn nói lại lựa chọn đi.',
    'AI-051': 'Bạn đã học xong chủ đề này rồi. Chọn chủ đề mới nha.',
    'AI-052': 'Bạn làm tốt lắm. HOMI đã thêm câu này vào ngôi sao!',
    'AI-053': 'HOMI chưa nghe rõ. Bạn nói lại đi.',
    'AI-054': 'Bạn tập trung nhé. Mình quay lại câu đang học nào.',
    'AI-055': 'Mình qua câu khác nha!',
    'AI-056': 'Gần được rồi! Bạn nghe lại câu này nhé.',
    'AI-057': 'Bây giờ bạn thử nói lại lần nữa nè.',
    'AI-058':
        'Bạn đã cố gắng tốt rồi! Mình sẽ luyện thêm sau. Giờ học câu tiếp nào.',
    'AI-059':
        'Chào bạn! Mình là HOMI. Hôm nay mình học bài “{tên bài}”. Bạn nghe HOMI trước rồi nói lại. Muốn nghe lại hoặc dừng thì bấm nút MAIN.',
    'AI-060': 'Hôm nay mình học bài “{tên bài}”. Bắt đầu thôi!',
    'AI-061': 'Mình học tiếp bài “{tên bài}”. Bắt đầu từ chỗ lúc trước.',
    'AI-062':
        'Giỏi lắm! Bạn đã học xong bài “{tên bài}”. Bạn muốn luyện lại từ đầu hay học bài tiếp theo?',
    'AI-063': 'Bạn đang ở câu đầu tiên rồi.',
    'AI-064': 'Bạn đang ở bài đầu tiên rồi.',
    'AI-065': 'Bạn nghe phần tổng quan thêm một chút nha.',
    'AI-066': 'Đây là phần tổng kết của bài học rồi.',
    'AI-067': 'HOMI chưa có bài tiếp theo.',
    'AI-068': 'Mình học xong bài hát này trước rồi chuyển phần khác.',
    'AI-069': 'HOMI nghe đây.',
    'AI-070': 'HOMI chưa thực hiện được. Bạn thử lại.',
  };

  static const Map<String, String> silencePromptById = <String, String>{
    'SIL-001':
        'Bạn có thể chọn: dịch sang tiếng Anh, học theo chủ đề hoặc học bộ từ vựng.',
    'SIL-002': 'Khi sẵn sàng, bạn nhấn nút gọi HOMI nhé.',
    'SIL-003': 'HOMI chưa nghe thấy bạn nói. Bạn nói lại đi.',
    'SIL-004': 'Mình dừng ở đây. Khi cần, bạn nhấn nút gọi HOMI nhé.',
    'SIL-005': 'HOMI chưa nghe thấy bạn nói. Bạn nói lại đi.',
    'SIL-006':
        'Ở đây hơi ồn. Bạn đưa micro lại gần, tránh hướng quạt hoặc chuyển sang chỗ yên hơn rồi thử lại nha.',
    'SIL-007': 'HOMI chưa nghe rõ. Bạn nói lại đi.',
    'SIL-008': 'Bạn nói lại lựa chọn nha.',
    'SIL-009': 'HOMI chưa nghe rõ. Bạn thử nói lại nhé.',
  };

  static const Map<String, HomiFallbackPolicy>
  fallbackPolicyById = <String, HomiFallbackPolicy>{
    'FB-001': HomiFallbackPolicy(
      id: 'FB-001',
      context: 'Chọn chức năng gốc',
      condition: 'Câu không khớp học chủ đề / từ mới / dịch',
      behavior:
          'Lặp lại: Bạn muốn dịch sang tiếng Anh, học theo chủ đề hay học bộ từ vựng?',
      exampleChildUtterance: 'Mình muốn đi chơi',
      firstPrompt:
          'Bạn có thể chọn: dịch sang tiếng Anh, học theo chủ đề hoặc học bộ từ vựng.',
      firstAction: 'Mở mic lại',
      secondPrompt:
          'HOMI vẫn chưa hiểu. Khi sẵn sàng, bạn nhấn nút gọi HOMI nhé.',
      finalAction: 'Kết thúc phiên, giữ trạng thái an toàn',
      priority: 'Khẩn cấp',
      status: 'Đề xuất; chưa có trong code',
    ),
    'FB-004': HomiFallbackPolicy(
      id: 'FB-004',
      context: 'Chọn chủ đề',
      condition: 'Không có số hoặc số ngoài phạm vi',
      behavior: 'Đọc lại khoảng số hợp lệ',
      exampleChildUtterance: 'Mình thích động vật',
      firstPrompt: 'Bạn nói số chủ đề, ví dụ “chủ đề số 3”.',
      firstAction: 'Mở mic lại',
      secondPrompt:
          'HOMI chưa nhận được chủ đề. Bạn có thể chọn trên điện thoại nha.',
      finalAction: 'Giữ màn danh sách chủ đề',
      priority: 'Cao',
      status: 'Có thể phát triển nhận tên chủ đề ở giai đoạn sau',
    ),
    'FB-005': HomiFallbackPolicy(
      id: 'FB-005',
      context: 'Chọn bài',
      condition: 'Không có số hoặc số ngoài phạm vi',
      behavior: 'Đọc lại khoảng số bài hợp lệ',
      exampleChildUtterance: 'Mình muốn bài về trường học',
      firstPrompt: 'Bạn nói số bài, ví dụ “bài số 1”.',
      firstAction: 'Mở mic lại',
      secondPrompt:
          'HOMI chưa nhận được bài. Bạn có thể chọn trên điện thoại nha.',
      finalAction: 'Giữ màn chủ đề',
      priority: 'Cao',
      status: 'Có thể phát triển nhận tên bài ở giai đoạn sau',
    ),
    'FB-006': HomiFallbackPolicy(
      id: 'FB-006',
      context: 'Trong bài luyện nghe',
      condition: 'Câu không khớp nghe lại/ câu tiếp/câu trước/dừng',
      behavior: 'Lặp lại toàn bộ câu hỏi điều hướng trong bài',
      exampleChildUtterance: 'Mình muốn đi chơi',
      firstPrompt:
          'HOMI chưa hiểu. Bạn có thể nói: nghe lại, câu tiếp, câu trước hoặc dừng lại.',
      firstAction: 'Mở mic lại và giữ nguyên câu',
      secondPrompt: 'HOMI vẫn chưa hiểu. Mình giữ nguyên câu hiện tại nhé.',
      finalAction: 'Resume câu hiện tại; không tự chuyển sai',
      priority: 'Khẩn cấp',
      status:
          'Đúng ví dụ người dùng nêu; tránh câu “Con tập trung học đi” quá cứng',
    ),
    'FB-007': HomiFallbackPolicy(
      id: 'FB-007',
      context: 'Xác nhận học lại chủ đề',
      condition: 'Không khớp Có/Không',
      behavior: 'Hỏi lại và yêu cầu nói có hoặc không',
      exampleChildUtterance: 'Mình muốn bài khác',
      firstPrompt: 'Bạn nói “có” để học lại hoặc “không” để chọn chủ đề khác.',
      firstAction: 'Mở mic lại',
      secondPrompt:
          'HOMI chưa nhận được câu trả lời. Bạn chọn “có” hoặc “không” nhé.',
      finalAction: 'Quay về danh sách chủ đề',
      priority: 'Trung bình',
      status: 'Đề xuất mặc định an toàn sau 2 lần',
    ),
    'FB-008': HomiFallbackPolicy(
      id: 'FB-008',
      context: 'Từ vựng: chọn luyện lại/ngôi sao',
      condition: 'Không khớp hai bộ',
      behavior: 'Lặp lại câu hỏi hiện tại',
      exampleChildUtterance: 'Mình muốn chơi',
      firstPrompt: 'Bạn nói “luyện lại” hoặc “ngôi sao”.',
      firstAction: 'Mở mic lại',
      secondPrompt:
          'Mình tạm dừng học bộ từ vựng. Khi sẵn sàng, bạn nhấn nút gọi HOMI nhé.',
      finalAction: 'Kết thúc luồng từ vựng',
      priority: 'Trung bình',
      status: 'Đề xuất fallback hai cấp',
    ),
    'FB-009': HomiFallbackPolicy(
      id: 'FB-009',
      context: 'Dịch liên tục',
      condition: 'Trẻ nói lệnh khác hoạt động hoặc dừng',
      behavior:
          'Một số cụm đã được tách khỏi pipeline dịch; câu khác vẫn có thể bị dịch như nội dung',
      exampleChildUtterance: 'Mình muốn học bài',
      firstPrompt:
          'Bạn muốn dừng dịch để học theo chủ đề hoặc học bộ từ vựng phải không?',
      firstAction: 'Xác nhận chuyển luồng; không dịch câu lệnh',
      secondPrompt: 'Bạn nói “dừng lại” để gọi HOMI nhé.',
      finalAction: 'Giữ chế độ dịch hoặc dừng theo lựa chọn rõ',
      priority: 'Khẩn cấp',
      status: 'Cần test tránh dịch nhầm lệnh điều hướng thành câu tiếng Anh',
    ),
    'FB-010': HomiFallbackPolicy(
      id: 'FB-010',
      context: 'Hoàn tất bài',
      condition: 'Không khớp Luyện lại từ đầu/Bài tiếp theo',
      behavior: 'Nói: Nói lại lựa chọn của bạn',
      exampleChildUtterance: 'Mình muốn về nhà',
      firstPrompt: 'Bạn nói “luyện lại từ đầu” hoặc “bài tiếp theo”.',
      firstAction: 'Mở mic lại',
      secondPrompt:
          'Mình dừng ở đây. Khi muốn học tiếp, bạn nhấn nút gọi HOMI nha.',
      finalAction: 'Giữ tiến độ hoàn thành và thoát an toàn',
      priority: 'Cao',
      status: 'Đề xuất thêm giới hạn retry',
    ),
  };

  /// Case-, accent-, and punctuation-insensitive normalization.
  static String normalizeVietnamese(String value) {
    var normalized = value.trim().toLowerCase();
    const replacements = <String, String>{
      'a': 'àáạảãâầấậẩẫăằắặẳẵ',
      'e': 'èéẹẻẽêềếệểễ',
      'i': 'ìíịỉĩ',
      'o': 'òóọỏõôồốộổỗơờớợởỡ',
      'u': 'ùúụủũưừứựửữ',
      'y': 'ỳýỵỷỹ',
      'd': 'đ',
    };
    for (final entry in replacements.entries) {
      normalized = normalized.replaceAll(RegExp('[${entry.value}]'), entry.key);
    }
    return normalized
        .replaceAll(RegExp(r'[^a-z0-9]+'), ' ')
        .replaceAll(RegExp(r'\s+'), ' ')
        .trim();
  }

  /// Returns true only when the entire normalized transcript matches.
  static bool matchesWholePhrase(String transcript, String phrase) {
    final normalizedTranscript = normalizeVietnamese(transcript);
    final normalizedPhrase = normalizeVietnamese(phrase);
    return normalizedTranscript.isNotEmpty &&
        normalizedTranscript == normalizedPhrase;
  }

  static bool matchesChildPhrase(String intentId, String transcript) {
    final phrases = childPhrasesByIntent[intentId] ?? const <String>[];
    return phrases.any((phrase) => matchesWholePhrase(transcript, phrase));
  }
}
